# https://prettier.io/docs/en/options.html
---

# Rules
bracketSpacing: true
jsxBracketSameLine: false
printWidth: 80
rcVerbose: true
singleQuote: true
tabWidth: 2
useTabs: false
trailingComma: 'es5'
